const html = `
        <div class="main-container">
            <header class="game-header">
                <div class="game-title-container">
                    <h1 class="game-title">BATTLESHIP</h1>
                </div>
                <h2 class="status"></h2>
                <a href="#" class="set-ships-screen-volume"></a>
                <a href="#" class="change-axis"></a>
            </header>
            <div class="set-ships-board">
                <div class="cell player A1"></div>
                <div class="cell player A2"></div>
                <div class="cell player A3"></div>
                <div class="cell player A4"></div>
                <div class="cell player A5"></div>
                <div class="cell player A6"></div>
                <div class="cell player A7"></div>
                <div class="cell player A8"></div>
                <div class="cell player A9"></div>
                <div class="cell player A10"></div>
                <div class="cell player B1"></div>
                <div class="cell player B2"></div>
                <div class="cell player B3"></div>
                <div class="cell player B4"></div>
                <div class="cell player B5"></div>
                <div class="cell player B6"></div>
                <div class="cell player B7"></div>
                <div class="cell player B8"></div>
                <div class="cell player B9"></div>
                <div class="cell player B10"></div>
                <div class="cell player C1"></div>
                <div class="cell player C2"></div>
                <div class="cell player C3"></div>
                <div class="cell player C4"></div>
                <div class="cell player C5"></div>
                <div class="cell player C6"></div>
                <div class="cell player C7"></div>
                <div class="cell player C8"></div>
                <div class="cell player C9"></div>
                <div class="cell player C10"></div>
                <div class="cell player D1"></div>
                <div class="cell player D2"></div>
                <div class="cell player D3"></div>
                <div class="cell player D4"></div>
                <div class="cell player D5"></div>
                <div class="cell player D6"></div>
                <div class="cell player D7"></div>
                <div class="cell player D8"></div>
                <div class="cell player D9"></div>
                <div class="cell player D10"></div>  
                <div class="cell player E1"></div>
                <div class="cell player E2"></div>
                <div class="cell player E3"></div>
                <div class="cell player E4"></div>
                <div class="cell player E5"></div>
                <div class="cell player E6"></div>
                <div class="cell player E7"></div>
                <div class="cell player E8"></div>
                <div class="cell player E9"></div>
                <div class="cell player E10"></div>
                <div class="cell player F1"></div>
                <div class="cell player F2"></div>
                <div class="cell player F3"></div>
                <div class="cell player F4"></div>
                <div class="cell player F5"></div>
                <div class="cell player F6"></div>
                <div class="cell player F7"></div>
                <div class="cell player F8"></div>
                <div class="cell player F9"></div>
                <div class="cell player F10"></div>
                <div class="cell player G1"></div>
                <div class="cell player G2"></div>
                <div class="cell player G3"></div>
                <div class="cell player G4"></div>
                <div class="cell player G5"></div>
                <div class="cell player G6"></div>
                <div class="cell player G7"></div>
                <div class="cell player G8"></div>
                <div class="cell player G9"></div>
                <div class="cell player G10"></div>
                <div class="cell player H1"></div>
                <div class="cell player H2"></div>
                <div class="cell player H3"></div>
                <div class="cell player H4"></div>
                <div class="cell player H5"></div>
                <div class="cell player H6"></div>
                <div class="cell player H7"></div>
                <div class="cell player H8"></div>
                <div class="cell player H9"></div>
                <div class="cell player H10"></div>
                <div class="cell player I1"></div>
                <div class="cell player I2"></div>
                <div class="cell player I3"></div>
                <div class="cell player I4"></div>
                <div class="cell player I5"></div>
                <div class="cell player I6"></div>
                <div class="cell player I7"></div>
                <div class="cell player I8"></div>
                <div class="cell player I9"></div>
                <div class="cell player I10"></div>
                <div class="cell player J1"></div>
                <div class="cell player J2"></div>
                <div class="cell player J3"></div>
                <div class="cell player J4"></div>
                <div class="cell player J5"></div>
                <div class="cell player J6"></div>
                <div class="cell player J7"></div>
                <div class="cell player J8"></div>
                <div class="cell player J9"></div>
                <div class="cell player J10"></div>
            </div>
        </div>
        `;
export default html;